#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-zoo
Version  : 1.7
Release  : 24
URL      : http://cran.r-project.org/src/contrib/zoo_1.7-11.tar.gz
Source0  : http://cran.r-project.org/src/contrib/zoo_1.7-11.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 GPL-3.0
BuildRequires : clr-R-helpers

%description
No detailed description available

%prep
%setup -q -c -n zoo

%build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/lib64/R/library
R CMD INSTALL zoo -l %{buildroot}/usr/lib64/R/library
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/zoo/CITATION
/usr/lib64/R/library/zoo/DESCRIPTION
/usr/lib64/R/library/zoo/INDEX
/usr/lib64/R/library/zoo/Meta/Rd.rds
/usr/lib64/R/library/zoo/Meta/demo.rds
/usr/lib64/R/library/zoo/Meta/hsearch.rds
/usr/lib64/R/library/zoo/Meta/links.rds
/usr/lib64/R/library/zoo/Meta/nsInfo.rds
/usr/lib64/R/library/zoo/Meta/package.rds
/usr/lib64/R/library/zoo/Meta/vignette.rds
/usr/lib64/R/library/zoo/NAMESPACE
/usr/lib64/R/library/zoo/NEWS
/usr/lib64/R/library/zoo/R/zoo
/usr/lib64/R/library/zoo/R/zoo.rdb
/usr/lib64/R/library/zoo/R/zoo.rdx
/usr/lib64/R/library/zoo/THANKS
/usr/lib64/R/library/zoo/TODO
/usr/lib64/R/library/zoo/WISHLIST
/usr/lib64/R/library/zoo/demo/zoo-overplot.R
/usr/lib64/R/library/zoo/doc/MSFT.rda
/usr/lib64/R/library/zoo/doc/demo1.txt
/usr/lib64/R/library/zoo/doc/demo2.txt
/usr/lib64/R/library/zoo/doc/index.html
/usr/lib64/R/library/zoo/doc/sunw.rda
/usr/lib64/R/library/zoo/doc/zoo-design.R
/usr/lib64/R/library/zoo/doc/zoo-design.Rnw
/usr/lib64/R/library/zoo/doc/zoo-design.pdf
/usr/lib64/R/library/zoo/doc/zoo-faq.R
/usr/lib64/R/library/zoo/doc/zoo-faq.Rnw
/usr/lib64/R/library/zoo/doc/zoo-faq.pdf
/usr/lib64/R/library/zoo/doc/zoo-quickref.R
/usr/lib64/R/library/zoo/doc/zoo-quickref.Rnw
/usr/lib64/R/library/zoo/doc/zoo-quickref.pdf
/usr/lib64/R/library/zoo/doc/zoo-read.R
/usr/lib64/R/library/zoo/doc/zoo-read.Rnw
/usr/lib64/R/library/zoo/doc/zoo-read.pdf
/usr/lib64/R/library/zoo/doc/zoo.Rnw
/usr/lib64/R/library/zoo/doc/zoo.pdf
/usr/lib64/R/library/zoo/help/AnIndex
/usr/lib64/R/library/zoo/help/aliases.rds
/usr/lib64/R/library/zoo/help/paths.rds
/usr/lib64/R/library/zoo/help/zoo.rdb
/usr/lib64/R/library/zoo/help/zoo.rdx
/usr/lib64/R/library/zoo/html/00Index.html
/usr/lib64/R/library/zoo/html/R.css
/usr/lib64/R/library/zoo/libs/zoo.so
